FROM python:3.11

WORKDIR /app
COPY . /app

RUN pip install --upgrade pip
RUN pip install poetry
RUN poetry config virtualenvs.create false \
    && poetry install --no-root

CMD ["uvicorn", "gridiron_guru_api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
